### ISSUE TITLE
Calendar always shows rain

### ISSUE THREAD

**Issue by DCunnama** [allanlaal/weather-calendar-feed#1]
Hi there, great app by the way.

One issue, I'm using it for Cape Town and the icon is always a rainy umbrella, even on sunny days.

http://weather.is.not.permanent.ee/?location=South_Africa/Western_Cape/Cape_Town&filename=weather.ics

Any ideas?

Thanks,
Daniel

**Comment by allanlaal** [comment]
the umbrella was initially meant to be the icon for rainfall, but thats a great idea!
I replaced the umbrella with ㎜ and replaced the whitespace between temperature and rainfall with an icon that represents that days weather:
- ❄ = Temperature below 0°C with snow/rain
- ⛄ = Temperature below 0°C without any rain
- ☔ = Temperature above 0°C with rain
- ☀ = Temperature above 0°C without any rain

Fixed by 5c69101e06ac2343f8bbd6ffc7c4802d8e098fa9

**Comment by DCunnama** [comment]
Thanks, it looks really good now!
